### PR TITLE
docker container added

### PR DESCRIPTION
**Pull request by antonkulaga**
Installing freesasa and haddock-tools dependencies is a pain, I made a docker container to make things easier for the user. So far I published it at my account but ready to transfer to whatever organizational account you have for haddock.
In my plans also creating a docker container for antibody protocol that will depend on haddock-tools container

### CODE REVIEW

**Comment by amjjbonvin** [comment]
We never had issues installing `freesasa` using simply `pip install freesasa` - So I would keep things in your own repo.

**Comment by antonkulaga** [comment]
The major use-case for docker is bioinformatic pipelines where everything is dockerized as it is a standard de facto in the field. So the docker container is suggested not as a substitute to using repository but for pipeline users.

**Comment by antonkulaga** [comment]
@amjjbonvin I plan to dockerize several haddock of protocols. Just let me know the lab policy. I can make PRs to corresponding protocols with dockerfile or I can just make separate repositories for docker containers.

**Comment by amjjbonvin** [comment]
Do you mean to dockerize the various tutorials we have?  At least the ones requiring some command line commands?

You would have to also provide clear instructions on how to use those and any requirements (e.g. Docker obviously :-)

**Comment by rvhonorato** [comment]
> @amjjbonvin I plan to dockerize several haddock of protocols.

Out of curiosity, why?

**Comment by antonkulaga** [comment]
>Out of curiosity, why?

Because I plan to automate some of the protocols and for automation, and having tools dockerized instead of installing on the host machine is considered to be among best practices.

>Do you mean to dockerize the various tutorials we have?

I mostly mean the protocols I want to automate for our lab, I mean at least https://github.com/haddocking/HADDOCK-antibody-antigen

**Pull request closed without merging**
