### PR TITLE
Add create_cif.py

### PR DESCRIPTION
**Pull request by rvhonorato**
This adds the `create_cif.py` script and its documentation, it is a standalone port of the webserver machinery to generate `.cif` files. 

The input is a run_directory, it reads data from `/data` and from the `job_params.json` inside the run dir, the output is the same as the one produced by the server.

```
python3 create_cif.py /Users/rodrigo/projects/cif_parser/47518-cif 
[23/02/2021 14:01:16] INFO Converting the cluster*.pdb structures to .cif
[23/02/2021 14:01:16] INFO Looking for models in /Users/rodrigo/projects/cif_parser/47518-cif
[23/02/2021 14:01:16] INFO Found 4 structures
[23/02/2021 14:01:16] INFO Looking for the tblfile field in /Users/rodrigo/projects/cif_parser/47518-cif/job_params.json
[23/02/2021 14:01:16] INFO tblfile field found, extracting information
[23/02/2021 14:01:16] INFO Converting /Users/rodrigo/projects/cif_parser/47518-cif/cluster1_1.pdb
[23/02/2021 14:01:19] INFO Saving as cluster1_1.cif
[23/02/2021 14:01:20] INFO Converting /Users/rodrigo/projects/cif_parser/47518-cif/cluster1_2.pdb
[23/02/2021 14:01:23] INFO Saving as cluster1_2.cif
[23/02/2021 14:01:24] INFO Converting /Users/rodrigo/projects/cif_parser/47518-cif/cluster1_3.pdb
[23/02/2021 14:01:28] INFO Saving as cluster1_3.cif
[23/02/2021 14:01:29] INFO Converting /Users/rodrigo/projects/cif_parser/47518-cif/cluster1_4.pdb
[23/02/2021 14:01:32] INFO Saving as cluster1_4.cif
```

### CODE REVIEW

**Review by amjjbonvin — APPROVED** [review]
Looking good - does it reads in both ambiguous and unambiguous restraints?

**Comment by rvhonorato** [comment]
For now only ambig, also on the webserver..!

**Comment by amjjbonvin** [comment]
Ok - noted - would be good to also include the unambiguous restraints in the future.

**Comment by amjjbonvin** [comment]
May-be good to also add the dependencies for this script to work… e.g. ihm (and how to install it), since it does not work on my mac :-)

**Comment by rvhonorato** [comment]
It's already in the main [README](https://github.com/haddocking/haddock-tools#create_cifpy), better to also add it in the script?

**Comment by amjjbonvin** [comment]
Clear!

… I should actually read the README file from time to time…

**Comment by rvhonorato** [comment]
I'm surprised I remembered to write on it actually! :D

**Pull request merged**
