### PR TITLE
Fix typo in check for different compound

### LINKED ISSUE #16: Typo in the check for multiple molecules in the same chain
The `p_name` variable that checks whether we've moved to another compound in the same chain should be `p_aname` instead.

This affects the script `restrain_bodies.py`.

### PR DESCRIPTION
**Pull request by pkoukos**
This addresses a bug in restrain_bodies.py and closes #16

### CODE REVIEW

**Comment by amjjbonvin** [comment]
Could it be affecting too the HADDOCK server? 
If the server uses this script.

**Comment by pkoukos** [comment]
It does exist on bianca at /trinity/home/enmr/software/haddock-tools/restrain_bodies.py. Not sure if it’s actually used or what’s happening on other machines.

I think it would only be triggered when you have mixtures, ie Nucleic acids + protein in the same chain as in this case which shouldn’t be too often.

**Comment by mtrellet** [comment]
As far as I know, it is not used in haddock2.4 server, the `PDBParser` class has its own `retrain_bodies` function. I just checked and no sign of `aname`.

**Comment by rvhonorato** [comment]
> The PDBParser class has its own `retrain_bodies` function.

`restrain_bodies` :P

**Pull request merged**
